apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-service
  name: vote-service
  namespace: vote
spec:
  ports:
  - name: 5000-80
    port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote
  type: NodePort
