apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: configuration
spec:
  volumes:
  - name: config-volume
    configMap:
      name: configuration
  containers:
    - name: test-container
      image: nginx
      envFrom:
      - secretRef:
          name: mysql-secret
