apiVersion: v1
kind: Pod
metadata:
  name: website
  namespace: www
spec:
  containers:
    - name: www-container
      image: nginx
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: www
