# kubectl create secret docker-registry regcred --docker-server=quay.io --docker-username=dridi_walid --docker-password=blabla--docker-email=contact@pocteo.co --dry-run -o yaml
apiVersion: v1
data:
  .dockerconfigjson: # Generate using kubectl create secret .....
kind: Secret
metadata:
  name: regcred
  namespace: configuration
type: kubernetes.io/dockerconfigjson
